export const TOKENS = {
  AUTH_REPOSITORY: Symbol('AUTH_REPOSITORY'),
  USER_REPOSITORY: Symbol('USER_REPOSITORY'),
  DOCTOR_REPOSITORY: Symbol('DOCTOR_REPOSITORY'),
  AVAILABILITY_REPOSITORY: Symbol('AVAILABILITY_REPOSITORY'),
  BOOKING_REPOSITORY: Symbol('BOOKING_REPOSITORY'),
} as const;
