export const TOKENS = {
    USER_REPOSITORY: Symbol('USER_REPOSITORY'),
    AUTH_REPOSITORY: Symbol('AUTH_REPOSITORY'),
    DOCTOR_REPOSITORY: Symbol('DOCTOR_REPOSITORY'),
    BOOKING_REPOSITORY: Symbol('BOOKING_REPOSITORY'),
};